spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: tawkenskiy000@gmail.com
    password: ehsn bzua nptv whdz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


telegram:
  bot:
    token: 8156975480:AAFJAuakJzrlklQe5PtifnIoNRFzhCVji00
    username: IslomW_bot



  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9094
      # key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: notification-events-topic
      properties:
        spring:
          json:
            trusted:
              packages: com.sharipov.notification-service.event

#server:
#  port: 0

